apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>KCA Demo App</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <style>
        body {
          margin: 0;
          font-family: "Segoe UI", Roboto, Arial, sans-serif;
          background: linear-gradient(135deg, #1e3c72, #2a5298);
          color: #333;
        }

        .container {
          max-width: 1200px;
          margin: 40px auto;
          background: #ffffff;
          padding: 40px;
          border-radius: 16px;
          box-shadow: 0 15px 40px rgba(0,0,0,0.2);
        }

        h1 {
          margin-top: 0;
          font-size: 32px;
          color: #1e3c72;
        }

        h2 {
          margin-top: 0;
          color: #2a5298;
          border-bottom: 2px solid #e5e5e5;
          padding-bottom: 6px;
          margin-bottom: 12px;
        }

        ul {
          line-height: 1.8;
        }

        .highlight {
          background: #f4f8ff;
          padding: 4px 8px;
          border-radius: 6px;
        }

        /* Flex layout for architecture + table */
        .content-row {
          display: flex;
          gap: 20px;
          margin-top: 20px;
          flex-wrap: wrap;  /* stack on smaller screens */
        }

        .architecture-wrapper {
          flex: 1 1 33%;
        }

        .architecture {
          text-align: center;
          letter-spacing: 2px;
          padding: 20px;
          background: #f7f9fc;
          border-radius: 12px;
          font-family: monospace;
          white-space: pre-line;
          line-height: 1.0;
          font-size: 1.4em;
          border-left: 6px solid #2a5298;
        }

        table {
          flex: 1 1 66%;
          width: 100%;
          border-collapse: collapse;
          border-radius: 12px;
          overflow: hidden;
          box-shadow: 0 5px 20px rgba(0,0,0,0.1);
        }

        th {
          background: #2a5298;
          color: white;
          padding: 12px;
          text-align: left;
          font-weight: 600;
        }

        td {
          padding: 10px;
          border-bottom: 1px solid #e5e5e5;
        }

        tr:nth-child(even) {
          background: #f9fbff;
        }

        tr:hover {
          background: #eef3ff;
          transition: 0.2s ease;
        }

        footer {
          margin-top: 40px;
          font-size: 14px;
          color: #777;
          text-align: center;
        }

        @media (max-width: 768px) {
          .content-row {
            flex-direction: column;
          }
          .architecture-wrapper, table {
            flex: 1 1 100%;
          }
        }
      </style>
    </head>

    <body>
      <div class="container">
        <h1>KCA Demo Application</h1>

        <p>
          This app demonstrates deployment on a 
          <span class="highlight">self-hosted single-node Kubernetes cluster (AWS EC2)</span>.
        </p>

        <h2>Components</h2>
        <ul>
          <li><strong>Frontend:</strong> Nginx serving static HTML via ConfigMap</li>
          <li><strong>Backend:</strong> Dockerized Node.js REST API</li>
          <li><strong>MongoDB:</strong> StatefulSet with credentials stored in Secret</li>
          <li><strong>Storage:</strong> Persistent Volume (PVC)</li>
        </ul>

        <div class="content-row">
          <div class="architecture-wrapper">
            <h2>Application Architecture</h2>
            <div class="architecture">
    <b>Browser</b>

     |

    <b>AWS Route53 (DNS)</b>
    
     |   

    <b>EC2 Public IP</b>

     |
       
    <b>Nginx Reverse Proxy</b>
       
     |

    <b>Ingress Controller (NodePort)</b>

     |

    <b>Ingress Routing Rules</b>

     |       

    <b>Frontend Service</b>  -   <b>Backend Service</b>  -   <b>MongoDB StatefulSet</b>
                                         
                                            |

                                  <b>Persistent Volume (PVC)</b>
                                  <b>Secret (DB credentials)</b>
            </div>
          </div>

          <div>
            <h2>MongoDB Test Data</h2>
            <table id="table">
              <thead>
                <tr>
                  <th>col1</th>
                  <th>col2</th>
                  <th>col3</th>
                  <th>col4</th>
                  <th>col5</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        </div>

        <footer>
          KCA Demo - Kubernetes - Ingress - MongoDB - AWS EC2
        </footer>
      </div>

      <script>
        // Fetch MongoDB test data from backend
        fetch("/data")
          .then(res => res.json())
          .then(data => {
            let tbody = document.querySelector("#table tbody");
            data.forEach(row => {
              let tr = document.createElement("tr");
              ["col1","col2","col3","col4","col5"].forEach(key => {
                let td = document.createElement("td");
                td.textContent = row[key];
                tr.appendChild(td);
              });
              tbody.appendChild(tr);
            });
          })
          .catch(err => console.error("Error fetching data:", err));
      </script>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html
        configMap:
          name: frontend-html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
