apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_USER: {{ .Values.mongo.username }}
  MONGO_PASSWORD: {{ .Values.mongo.password }}
  MONGO_DB: {{ .Values.mongo.database }}

